# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    rebase-strategy: auto
    auto-merge: false
registries:
  maven:
    type: maven
    url: https://api.mapbox.com/downloads/v2/releases/maven
    username: mapbox
    password: sk.eyJ1IjoiZWx2YWgtbm9ucHJvZCIsImEiOiJja3JuOWRkZHIwYmJsMzJvOWNicW5pcDkwIn0.coHNbzDtfMh79Oc-pY7mDA

